{ pkgs, config, ... }:

{
  home = {
    packages = with pkgs; [
      slurp
      grim
      julia-bin
      angband
      anki
      audacity
      bitwarden
      bk
      brave
      cargo
      cinnamon.nemo
      cryptsetup
      deno
      discord
      distrobox
      dunst
      eza
      feh
      ffmpeg-full
      file
      fzf
      gcc
      gimp
      go
      htmlq
      htop
      hypridle
      hyprlock
      imagemagick
      jq
      libqalculate
      luajitPackages.magick
      lutris
      lxappearance
      maim
      mangal
      mpc-cli
      mpd
      mpv
      newsboat
      nodejs
      nodePackages_latest.bash-language-server
      nodePackages_latest.pyright
      nodePackages_latest.readability-cli
      nsxiv
      nyxt
      openssl
      pass
      passExtensions.pass-tomb 
      pinentry
      pkg-config
      popcorntime
      porsmo
      prismlauncher
      pulsemixer
      python3
      qalculate-gtk
      qbittorrent
      rust-analyzer
      rustc
      sc-im
      slides
      socat
      steamPackages.steamcmd
      swaybg
      telegram-desktop
      texlive.combined.scheme-full
      thunderbird
      tofi
      tomb
      tuir
      ueberzugpp
      unrar-wrapper
      unzip
      wezterm
      wiki-tui
      wineWowPackages.staging
      wl-clipboard
      xclip
      youtube-tui
      yt-dlp
      zip
    ];
  };

}
