{ pkgs, config, ... }:

{
  home = {
    packages = with pkgs; [
      angband
      #anki
      audacity
      bk
      brave
      cargo
      cryptsetup
      deno
      discord
      distrobox
      dunst
      eza
      feh
      ffmpeg-full
      file
      fzf
      gcc
      gimp
      go
      grim
      htmlq
      htop
      hypridle
      hyprlock
      imagemagick
      jq
      julia-bin
      libqalculate
      luajitPackages.magick
      lutris
      lxappearance
      maim
      mangal
      mpc-cli
      mpd
      mpv
      nemo
      newsboat
      nodePackages_latest.bash-language-server
      #nodePackages_latest.pyright
      nodePackages_latest.readability-cli
      nodejs
      nsxiv
      #nyxt
      openssl
      pass
      passExtensions.pass-tomb 
      pinentry
      pkg-config
      popcorntime
      porsmo
      prismlauncher
      pulsemixer
      python3
      qalculate-gtk
      qbittorrent
      rust-analyzer
      rustc
      sc-im
      slides
      slurp
      socat
      steamPackages.steamcmd
      swaybg
      #telegram-desktop
      ##  texlive.combined.scheme-full
      thunderbird
      tofi
      tomb
      tuir
      ueberzugpp
      unrar-wrapper
      unzip
      vkd3d-proton
      vlc
      wiki-tui
      wineWowPackages.staging
      winetricks
      wl-clipboard
      xclip
      youtube-tui
      yt-dlp
      zip
    ];
  };

}
